spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
spring-doc:
  swagger-ui:
    enabled: true
feign:
  client:
    config:
      default:
        loggerLevel: full
  name:
    site: apidesafio
  url:
    site: http://localhost:8081/
